name: Team awesome's approval workflow
on: pull_request_review
jobs:
  labelWhenApproved:
    name: Label when approved
    runs-on: ubuntu-latest

    steps:
      - uses: pullreminders/label-when-approved-action@master
      - name: My first workflow
        env:
          APPROVALS: "1"
          GITHUB_TOKEN: "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"
          ADD_LABEL: "My workflow label"
          TESTENV: "TEST"
